/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cinbo_filesync_TestJniMain */

#ifndef _Included_com_cinbo_filesync_TestJniMain
#define _Included_com_cinbo_filesync_TestJniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cinbo_filesync_TestJniMain
 * Method:    HelloWord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cinbo_filesync_TestJniMain_HelloWord
  (JNIEnv *, jclass);

/*
 * Class:     com_cinbo_filesync_TestJniMain
 * Method:    cToJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cinbo_filesync_TestJniMain_cToJava
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
